### ISSUE TITLE
Gen-Splitter does not work

### ISSUE THREAD

**Issue by TipoRick** [MetallicGoat/Gen-Splitting#5]
When trying to put the addon on the server together with MBedWars, I came across the fact that the addon does not work. 

For a long time I tried to fix the problem myself by selecting the versions of the addon and plugin and digging into configs and folders, but everything leads to one thing - the addon works properly, but there are no signs of functionality in it

Addon version: 4.3.1
Plugin version: 5.4.13
Server version: Paper 1.8.9
Java: 8 (321)
![image](https://github.com/user-attachments/assets/1c2c9ab9-edd6-4d4c-babe-4b22d39d69c7)
![image](https://github.com/user-attachments/assets/f8542ccf-555d-4653-8b06-ccba0d208621)
I hope there is a solution to this problem

**Comment by MetallicGoat** [comment]
Make sure it's enabled in the config, check the console for errors. The addon works fine, and is used by many people

**Comment by TipoRick** [comment]
> Make sure it's enabled in the config, check the console for errors. The addon works fine, and is used by many people

I noticed it. The item was also added to the list of config items. 
What can I send to determine the cause of the problem?
![image](https://github.com/user-attachments/assets/50bc8300-c655-4a1f-b1f0-88e1a1e2ba68)

**Comment by TipoRick** [comment]
I got it all wrong. I'm sorry for the trouble.
